name: firstDev.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run:
        npm install -g @angular/cli@latest
        npm i
        ng build --prod
        pm2 stop 0
        pm2 start 0
        pm2 save
        sudo systemctl restart nginx
