name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t ifedim/sheriff_assignment .
      - name: Publish image to docker hub
        run: docker push ifedim/sheriff_assignment:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ifedim/sheriff_assignment:latest
      - name: Delete old container
        run: docker rm -f sheriff_assignment-container
      - name: Run docker container
        run: docker run -d -p 80:80 --name sheriff_assignment-container ifedim/sheriff_assignment
